#!/usr/bin/env python
"""Train a tiny MLP to recognize 5x5 digit glyphs, quantize it to integers, and
emit the weights as ca65 tables for the 6502.

The integer forward pass defined here is the GOLDEN reference: the 6502 assembly
reproduces this exact arithmetic. Binary input means layer 1 is add-only; layer 2
uses an 8-bit by 8-bit multiply.
"""
import numpy as np
from sklearn.neural_network import MLPClassifier

rng = np.random.default_rng(0)

# ---------------------------------------------------------------------------
# 5x5 glyphs for digits 0..3 (1 = pixel on)
# ---------------------------------------------------------------------------
GLYPHS = {
    0: ["01110",
        "10001",
        "10001",
        "10001",
        "01110"],
    1: ["00100",
        "01100",
        "00100",
        "00100",
        "01110"],
    2: ["11110",
        "00001",
        "01110",
        "10000",
        "11111"],
    3: ["11110",
        "00001",
        "01110",
        "00001",
        "11110"],
}
N_IN, N_HID, N_OUT = 25, 8, 4


def to_vec(rows):
    return np.array([int(c) for r in rows for c in r], dtype=np.float64)


templates = {k: to_vec(v) for k, v in GLYPHS.items()}

# training set: each template plus random bit flips (jitter)
X, y = [], []
for label, vec in templates.items():
    for _ in range(80):
        v = vec.copy()
        flips = rng.choice(N_IN, size=rng.integers(0, 3), replace=False)
        v[flips] = 1 - v[flips]
        X.append(v); y.append(label)
X, y = np.array(X), np.array(y)

clf = MLPClassifier(hidden_layer_sizes=(N_HID,), activation="relu",
                    max_iter=4000, random_state=0)
clf.fit(X, y)
print("[train] float train accuracy:", clf.score(X, y))

W1f, W2f = clf.coefs_[0].T, clf.coefs_[1].T        # (8,25), (4,8)
b1f, b2f = clf.intercepts_[0], clf.intercepts_[1]  # (8,), (4,)

# ---------------------------------------------------------------------------
# quantize to integers
# ---------------------------------------------------------------------------
S1 = 64.0 / max(np.abs(W1f).max(), np.abs(b1f).max())   # layer-1 scale
W1 = np.clip(np.round(W1f * S1), -127, 127).astype(np.int16)
B1 = np.round(b1f * S1).astype(np.int32)
SHIFT1 = 5                                              # ReLU downshift to 0..~127

S2 = 31.0 / np.abs(W2f).max()                           # keep layer-2 sums in int16
W2 = np.clip(np.round(W2f * S2), -31, 31).astype(np.int16)
B2 = np.round(b2f * S2 * (1)).astype(np.int32)


def int_forward(xbits):
    """Exact integer forward pass -- the 6502 reproduces this."""
    h = np.zeros(N_HID, dtype=np.int32)
    for j in range(N_HID):
        acc = B1[j]
        for i in range(N_IN):
            if xbits[i]:
                acc += W1[j, i]                         # add-only (binary input)
        acc = acc >> SHIFT1                             # ReLU + downscale
        h[j] = max(0, min(127, acc))
    o = np.zeros(N_OUT, dtype=np.int32)
    for c in range(N_OUT):
        acc = B2[c]
        for j in range(N_HID):
            acc += h[j] * W2[c, j]                      # 8x8 -> 16 multiply
        o[c] = acc
    assert np.abs(o).max() < 32767, f"layer-2 overflows int16: {o}"
    return h, o


# verify integer net on the clean glyphs
print("[quant] integer-net predictions on clean glyphs:")
ok = True
for label, vec in templates.items():
    bits = vec.astype(int)
    h, o = int_forward(bits)
    pred = int(np.argmax(o))
    ok &= (pred == label)
    print(f"  digit {label}: pred {pred}  logits {list(o)}")
print("[quant] all correct:", ok)
assert ok, "integer net misclassifies a clean glyph -- retune scales/shift"

# ---------------------------------------------------------------------------
# emit ca65 tables; embed digit 2's glyph as the test input
# ---------------------------------------------------------------------------
TEST_LABEL = 2
test_bits = templates[TEST_LABEL].astype(int)


def w16(v):
    return v & 0xFFFF


lines = ["; auto-generated by eightbit_nn_train.py -- do not edit",
         f"N_IN = {N_IN}", f"N_HID = {N_HID}", f"N_OUT = {N_OUT}",
         f"SHIFT1 = {SHIFT1}", f"EXPECTED = {TEST_LABEL}", ""]
lines.append("; input glyph (25 bytes, 0/1) -- digit %d" % TEST_LABEL)
lines.append("INPUT:")
for r in range(5):
    row = test_bits[r * 5:(r + 1) * 5]
    lines.append("    .byte " + ",".join(str(int(b)) for b in row))
lines.append("")
lines.append("; W1[hidden][input] as signed bytes, row-major (8 x 25)")
lines.append("W1:")
for j in range(N_HID):
    lines.append("    .byte " + ",".join(str(int(W1[j, i]) & 0xFF) for i in range(N_IN)))
lines.append("; B1 (8 x int16, little-endian)")
lines.append("B1:")
lines.append("    .word " + ",".join(str(w16(int(B1[j]))) for j in range(N_HID)))
lines.append("; W2[out][hidden] signed bytes (4 x 8)")
lines.append("W2:")
for c in range(N_OUT):
    lines.append("    .byte " + ",".join(str(int(W2[c, j]) & 0xFF) for j in range(N_HID)))
lines.append("; B2 (4 x int16)")
lines.append("B2:")
lines.append("    .word " + ",".join(str(w16(int(B2[c]))) for c in range(N_OUT)))
lines.append("")

open("res/nn_weights.s", "w").write("\n".join(lines) + "\n")
print("[emit] wrote res/nn_weights.s ; expected class =", TEST_LABEL)
